apiVersion: v1
kind: Secret
metadata:
  name: agentic-secrets
  namespace: agentic
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "<BASE64_MYSQL_ROOT_PASSWORD>"
  GEMINI_API_KEY: "<BASE64_GEMINI_API_KEY>"
  LANGCHAIN_API_KEY: "<BASE64_LANGCHAIN_API_KEY>"
